import Head from "next/head";
import Image from "next/image";
import Button from "../components/button/button";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button type="button">Hello World!</Button>
        <Button type="button" hasBackground={false}>
          Hello World!
        </Button>
        <Button type="button">Hello World!</Button>
      </main>
    </div>
  );
}
